### ISSUE TITLE
New rtserver?

### ISSUE THREAD

**Issue by ksterne** [jspaleta/SuperDARN_MSI_ROS#12]
Whatca'll up to?  Seems like a python version of rtserver?  Anything I can help test out on Fort Hays? Just seeing some things come across my e-mail and wondering what's up.

**Comment by simonmr** [comment]
We're trying to get one set up that sends out json data. I'm still in the testing phase so not just yet but once I get up and running I'll let you know.

**Comment by ksterne** [comment]
Ah, sorry here, I just glanced at a few e-mails you and Ashton had sent around a little while ago about this.  I'm only on half time here now and it seems as though I'm not going to be able to keep up with some things.  If you get to a point where you'd like to test it out on the Fort Hays radars, let me know and I can help out with that.  Otherwise good luck!
